# Generated by Django 4.1.7 on 2023-04-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_puclic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='puclic',
            new_name='public',
        ),
    ]
